name: canteen
version: 0.1
summary: Minimalist Python (flask) web application setup using React
description: |
  Minimalist Python (flask) web application setup using React
confinement: strict
grade: devel

apps:
  canteen:
    command: bin/talisker --reload canteen.app:app
    plugs: [network-bind, network, mount-observe]

parts:
  canteen:
    plugin: python
    source: .
    requirements: requirements.txt
    prime:
      - -install
